# Generated by Django 5.2 on 2025-06-18 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("age", models.IntegerField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Мужской"), ("Female", "Женский")],
                        max_length=10,
                    ),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("Single", "Холост/Не замужем"),
                            ("Married", "Женат/Замужем"),
                            ("Divorced", "Разведен(а)"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "work_type",
                    models.CharField(
                        choices=[
                            ("Private", "Частный сектор"),
                            ("Self-employed", "Самозанятый"),
                            ("Government", "Госслужащий"),
                            ("Never_worked", "Не работал(а)"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "residence_type",
                    models.CharField(
                        choices=[("Urban", "Город"), ("Rural", "Село")], max_length=10
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hypertension", models.BooleanField(default=False)),
                ("heart_disease", models.BooleanField(default=False)),
                (
                    "average_glucose",
                    models.DecimalField(decimal_places=2, max_digits=6),
                ),
                ("bmi", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "smoking_status",
                    models.CharField(
                        choices=[
                            ("Non-smoker", "Не курит"),
                            ("Formerly smoked", "Бывший курильщик"),
                            ("Currently smokes", "Курит"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "alcohol_intake",
                    models.CharField(
                        choices=[
                            ("Never", "Никогда"),
                            ("Rarely", "Редко"),
                            ("Social Drinker", "Умеренно"),
                            ("Frequent Drinker", "Часто"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "physical_activity",
                    models.CharField(
                        choices=[
                            ("Low", "Низкая"),
                            ("Moderate", "Умеренная"),
                            ("High", "Высокая"),
                        ],
                        max_length=10,
                    ),
                ),
                ("stroke_history", models.BooleanField(default=False)),
                ("family_stroke_history", models.BooleanField(default=False)),
                ("blood_pressure", models.CharField(max_length=10)),
                ("hdl", models.IntegerField()),
                ("ldl", models.IntegerField()),
                (
                    "dietary_habits",
                    models.CharField(
                        choices=[
                            ("Vegan", "Веган"),
                            ("Vegetarian", "Вегетарианец"),
                            ("Pescatarian", "Пескетарианец"),
                            ("Paleo", "Палеодиета"),
                            ("Gluten-Free", "Без глютена"),
                            ("Non-Vegetarian", "Не вегетарианец"),
                        ],
                        max_length=20,
                    ),
                ),
                ("stress_level", models.DecimalField(decimal_places=2, max_digits=3)),
                ("symptoms", models.TextField(blank=True)),
                ("diagnosis", models.BooleanField(default=False)),
                (
                    "patient",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myteamprilozenie.patient",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prediction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("probability", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("VL", "Очень низкий"),
                            ("L", "Низкий"),
                            ("M", "Умеренный"),
                            ("H", "Высокий"),
                            ("VH", "Очень высокий"),
                        ],
                        max_length=2,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "medical_history",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myteamprilozenie.medicalhistory",
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myteamprilozenie.patient",
                    ),
                ),
            ],
        ),
    ]
